#SUNDAY: COMMENT ON EACH MENU FUNCTION AND LIST WHAT EACH SHOULD EXPECT TO DO
#		 BE SPECIFIC.
#		 ALSO READ ON HOW TO SAVE THINGS TO A DOCUMENT.
# READ IN THE CHORE LIST FROM THE DOC, AND SAVE THE CHORES/MEMBERS/ASSIGNED TO VARIABLES.

###		1. ENTER NEW CHORE
#				CHECK TO SEE IF EXISTING CHORE IS IN DOC.
#						
#		2. REMOVE CHORE
#		3. ENTER NEW MEMBER
#		5. REMOVE MEMBER
#		6. LIST CHORES
#		7. LIST MEMBERS
#		8. ASSIGN MEMBER'S CHORES
#		9. SAVE INTO DOCUMENT

menu = """***************************\n
		1. ENTER NEW CHORE\n
		2. REMOVE CHORE\n
		3. ENTER NEW MEMBER\n
		5. REMOVE MEMBER\n
		6. LIST CHORES\n
		7. LIST MEMBERS\n
		8. ASSIGN MEMBER'S CHORES\n
		9. SAVE INTO DOCUMENT\n
		***************************\n"""
		
print(menu)
